name: Feature Request
description: Suggest a new feature for VideoStream Library
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature for VideoStream Library!
        
        We welcome ideas that improve video I/O capabilities for embedded Linux applications.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the use case or limitation you're facing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
      placeholder: Describe alternative solutions or workarounds

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this affect?
      options:
        - Camera Capture (V4L2)
        - Hardware Encoding (H.264/H.265)
        - IPC Frame Sharing (Host/Client)
        - GStreamer Plugin (vslsink/vslsrc)
        - Python Bindings
        - Build System
        - Documentation
        - New Component
        - Other

  - type: dropdown
    id: platform
    attributes:
      label: Target Platform
      description: Which platforms would benefit?
      multiple: true
      options:
        - All platforms
        - NXP i.MX 95
        - NXP i.MX8M Plus
        - NXP i.MX8M
        - NXP i.MX8
        - Generic ARM64
        - Generic ARMv7
        - x86_64

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe your specific use case
      placeholder: |
        - Application: Edge AI inference pipeline
        - Requirements: Low latency frame sharing
        - Constraints: Power budget <5W

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature for your project?
      options:
        - Critical - Blocking our project
        - High - Needed soon
        - Medium - Would be helpful
        - Low - Nice to have

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information (links, examples, benchmarks, etc.)

  - type: checkboxes
    id: contribute
    attributes:
      label: Contribution
      options:
        - label: I'm willing to implement this feature
          required: false
        - label: I'm willing to test this feature
          required: false
        - label: I can provide hardware for testing
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I searched existing issues and didn't find a duplicate
          required: true
        - label: This feature aligns with VideoStream's scope (video I/O for embedded Linux)
          required: true
